#!/bin/bash
cd /opt/support
if [ ! -x /export/support/cvs ]; then
  if [ ! -d /export/support ]; then
    mkdir -p /export/support
  fi
  cp /opt/support/cvs /export/support/cvs
fi
bash tardis.sh $@

