#!/bin/bash
echo find and remove images with no tag and no repository name
echo ---
for i in $(docker images | grep '^[<]none[>] .*[<]none[>]' | sed -e 's/  [ ]*/:/g' | cut -f 3 -d :); do
  docker rmi $i
done
echo ...
